name: Create combined workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create Combined Notebook
        run: |
          echo "" > Combined_Notebooks/Automated_Combined_Notebook.ipynb
          cat Individual_Notebooks/Python-Notebooks/data-cleanup.ipynb >> Combined_Notebooks/Automated_Combined_Notebook.ipynb
          cat Individual_Notebooks/Python-Notebooks/clustering.ipynb >> Combined_Notebooks/Automated_Combined_Notebook.ipynb
          cat Individual_Notebooks/Python-Notebooks/pcoa.ipynb >> Combined_Notebooks/Automated_Combined_Notebook.ipynb
          cat Individual_Notebooks/Python-Notebooks/univariate-statistics.ipynb >> Combined_Notebooks/Automated_Combined_Notebook.ipynb
          
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'