name: Create combined workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create Combined Notebook
        run: |
          echo "" > Combined_Notebook.ipynb
          cat file1.py >> Combined_Notebook.ipynb
          cat file2.py >> Combined_Notebook.ipynb
          cat file3.py >> Combined_Notebook.ipynb
          cat file4.py >> Combined_Notebook.ipynb
          
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'