name: Create combined workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Overwrite file
        uses: "DamianReeves/write-file-actions@master"
        with:
          path: ${{ github.workspace }}/Combined_Notebooks/Combined_Analysis.ipynb
          write-mode: overwrite
          contents: |
          ${{ github.workspace }}/Individual_Notebooks/Python-Notebooks/data-cleanup.ipynb
          ${{ github.workspace }}/Individual_Notebooks/Python-Notebooks/clustering.ipynb
      
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
          force: true
          message: 'Overwritten by Github Actions - ${date}' 