name: Create combined workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: ".github/workflows/requirements.txt"

      - name: Create Combined Notebook
        run: |
          nbmerge Individual_Notebooks/Python-Notebooks/data-cleanup.ipynb Individual_Notebooks/Python-Notebooks/clustering.ipynb Individual_Notebooks/Python-Notebooks/pcoa.ipynb Individual_Notebooks/Python-Notebooks/univariate-statistics.ipynb > Combined_Notebooks/Automated_Combined_Notebook.ipynb
          
      - name: Commit Changes
        env:
            PAT: ${{ secrets.PatPush }}
        run: |
          git config --global user.name "Zquinlan"
          git config --global user.email "zquinlan@gmail.com"
          git add -A
          git commit -a -m "Update combined motebook notebook"
          
          git remote set-url origin https://github.com/Zquinlan/FBMN-STATS
          git push origin HEAD:${{ github.ref }} --force